### ISSUE TITLE
JSON parser errors with scoop

### ISSUE THREAD

**Issue by shakeyourbunny** [anderlli0053/DEV-tools#10]
## Bug Report
duplicati-client, gcc@10.3.0-multilib+x32, gcc@8.1.0-multilib+x32, gcc@8.1.0-x64+x32, gcc@9.2.0-multilib+x32, gcc@9.3.0-x64+x32, groff, msys2@2016-10-25, perl@5.10.1.1+gcc, perl@5.10.1.2+gcc, perl@5.12.1.0+gcc, perl@5.12.3.0+gcc, processing, python@2.7.15, python@2, python@3.7.1, python@3, python@mini-2.7.16, python@mini-3.7.3, python@mini-3.8.3, python@mini-3.8, python@mini, resourceHacker, resourceHacker@5.1.8, rsync, rsync@3.1.3-x32, rsync@3.2.3-x64

### Current Behaviour
JSON errors if I do a "scoop search x" with this bucket enabled.

### Expected Behaviour
No JSON errors.

### Additional context/output

WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\duplicati-client.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\gcc@10.3.0-multilib+x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\gcc@8.1.0-multilib+x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\gcc@8.1.0-x64+x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\gcc@9.2.0-multilib+x32.json.
+x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\gcc@9.3.0-x64+x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\groff.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\msys2@2016-10-25.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\perl@5.10.1.1+gcc.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\perl@5.10.1.2+gcc.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\perl@5.12.1.0+gcc.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\perl@5.12.3.0+gcc.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\processing.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@2.7.15.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@2.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@3.7.1.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@3.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@mini-2.7.16.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@mini-3.7.3.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@mini-3.8.3.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@mini-3.8.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\python@mini.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\resourceHacker.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\resourceHacker@5.1.8.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\rsync.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\rsync@3.1.3-x32.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\anderlli0053_DEV-tools\bucket\rsync@3.2.3-x64.json.

### System details

**Windows version:** [e.g. 7, 8, 10] 10

**OS architecture:** [e.g. 32bit, 64bit] 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PS C:\Users\pulaski> $($PSVersionTable.PSVersion)

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by anderlli0053** [comment]
@shakeyourbunny  Hmm.. thanks for the report.

When i try to search with command `scoop search x` it doesn't return any warning nor error while parsing / searching in this bucket.  It returns warnings in other ones. I checked some of the mentioned manifests in my bucket and all looks fine, maybe there are some foreign path names and other things in the manifests that cause this. I tried to install some of the mentioned apps and they work as they should.

![123](https://user-images.githubusercontent.com/22171451/183247811-ac516721-3597-4661-8051-14ef01e85163.jpg)



EDIT:  I found out that since this bucket fetches some manifests from other buckets, the said "warning corruption" happens there also.

So there is nothing wrong with the apps / manifests that you are warned about, they still work just fine, it just happens because of some comments inside JSON manifests, usually starting with `//`.  Now that comments are what different devs use to write down what the code does, and since this bucket is self-updating and fetching, even if i remove all the comments in the manifests, it will only work until the next BOT update (every 6 or so hours) or even when the new version of the specified erroneus app is released and then detected and fetched from the upstream BOT, which will overwrite all the comments and erroneus elements in manifest.

**Comment by shakeyourbunny** [comment]
Well, I found that in groff there IS a comment.

https://github.com/anderlli0053/DEV-tools/blob/840057c09e6caa54be9374204bdf7dbdf3a0cce3/bucket/groff.json#L13

My guess is that if this would be filtered out by your update checker, would be neat.

On the shell, I could catch these comments which produces the errors with:
````
grep "//" *.json | egrep -v "http(|s)://|note:|regex|checkver|UpdateUrl|appxbundle" | egrep "\{|\}|\[|\]"
````

**Comment by shakeyourbunny** [comment]
There is also a Github project which directly strips off all comments, making it valid JSON again. 

On the first look it looks empty, but you have to select the branch with the language of your choice to get it.

https://github.com/getify/JSON.minify/tree/master

**Comment by anderlli0053** [comment]
I'm trying to achieve something with "grepWin" tool on Windows. I'll see what can i do with RegEx 🙂

**Comment by shakeyourbunny** [comment]
I wrote a small python script, which cleans up the JSON files and does a syntactical check / linting of them, you can integrate it if you want.

https://gist.github.com/shakeyourbunny/48716963e2eca4adebb129b8995f2c39

Note that you have to install the json_minify python module (pip3 install json_minify) and edit the source path on line 26.

The script ran through and cleaned up the comments, but it also has found some other things that made the JSON not usable:

- there are some JSONs with weird encoding or are even incomplete/truncated (cabal.json, processing.json which made the files unusable, ignored by the script)
- there is a single JSON ALAC.json which has a weird byte order mark (corrected by the script)
- a certain author called Andrew Pozenel thinks that a string in JSON may go over multiple lines and tabulators are allowed (which is not allowed). Some of the files are listed in the python script, but is automatically corrected now.

After all that cleaning up the output of scoop now is more or less fixed:
````
 scoop search obs
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\zzz_anderlli0053\bucket\cabal.json.
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\zzz_anderlli0053\bucket\processing.json.
Results from local buckets...

Name               Version Source           Binaries
----               ------- ------           --------
obs-browser-plus   3.22.5  zzz_anderlli0053
obs-studio-small   21.1.2  zzz_anderlli0053
obs-studio         27.2.4  zzz_anderlli0053
obsidian           0.15.8  zzz_anderlli0053
OBSPortable        27.2.4  zzz_anderlli0053
OBSStudio-Portable 27.2.4  zzz_anderlli0053
obsutil            5.4.6   zzz_anderlli0053
streamlabs-obs     1.10.0  zzz_anderlli0053
````

It would be great if your update scripts ("robot") would do a cleanup after rounding up the updates :-)

**Comment by anderlli0053** [comment]
@shakeyourbunny  
Hey thanks for the Python script, although i get an error running `python3 cleanup-manifests.py`, inside "bucket" folder and got these errors

```
Traceback (most recent call last):
  File "C:\Users\ander\Desktop\DEV-tools\bucket\cleanup-manifests.py", line 60, in <module>
    cleanup_json(files.path)
  File "C:\Users\ander\Desktop\DEV-tools\bucket\cleanup-manifests.py", line 53, in cleanup_json
    json_dict = json.loads(json_clean)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
PS C:\Users\ander\Desktop\DEV-tools\bucket>
```


I'm guessing it kind of worked, since when i run it it comes to the " -> perl@5.10.1.1+gcc.json" and then the script errors out for some reason.. Hmm..

**Comment by shakeyourbunny** [comment]
The JSON is invalid and could not be processed.
https://github.com/anderlli0053/DEV-tools/blob/1a9c920e92526c711a12201d82962689ef3fe7ab/bucket/perl%405.10.1.1%2Bgcc.json#L8
see https://codebeautify.org/jsonvalidator/y22e3bc37

In a nutshell:
`````
	"hash": "sha256:9da0cc11166e13ce0a9077cb0b42c4909ed849647c094f71aebb2eaf7550bd68",}
````
There is a , at the end of the line. which is not legal in JSON.

**Comment by anderlli0053** [comment]
@shakeyourbunny  I had to modify your script a little as i was getting escape sequence error and also others, no big deal

i had to explicitly specify/import the path from the "os" module:

`from os import path`

_**( I don't know why the interpreter doesn't want to import the whole module classes, at least for me and for the path thing)**_

and set the clean path like so `clean_directory = (r"C:\\Users\\ander\\Desktop\\DEV-tools\\bucket")` so it takes raw input and double backslashes to work correctly. 

I've even reset the python3 by completely clean-reinstalling it but it still works strangely like that... at least it works 😄 


Console throws no more warnings for this bucket at least, please run `scoop update` and `scoop search x` and then test if there are some other warnings that show on your PC, but not on mine.

Thank you for your script

_**P.S.:**_

**_I'm keeping this open, until you report back about the status._**

**Comment by shakeyourbunny** [comment]
seems to work for the most part.

````
PS C:\Windows\System32\WindowsPowerShell\v1.0> scoop update
Updating Scoop...
Updating 'main' bucket...
 * df663b2cd simplex-chat: Update to version 3.1.0                       5 minutes ago
Updating 'zzz_anderlli0053' bucket...
Updating files: 100% (3021/3021), done.
 * 0f391276 Update cleanup-manifests.py                                  3 minutes ago
 * c8b30a69 Various fixes                                                26 minutes ago
Scoop was updated successfully!
PS C:\Windows\System32\WindowsPowerShell\v1.0> scoop search obs-studio
WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\zzz_anderlli0053\bucket\processing.json.
Results from local buckets...

Name             Version Source           Binaries
----             ------- ------           --------
obs-studio-small 21.1.2  zzz_anderlli0053
obs-studio       27.2.4  zzz_anderlli0053
````

the thing with processing.json is to be expected, but I'm curious why your Python installation freaked out.

Thank you for your efforts!

**Comment by anderlli0053** [comment]
> seems to work for the most part.
> 
> ```
> PS C:\Windows\System32\WindowsPowerShell\v1.0> scoop update
> Updating Scoop...
> Updating 'main' bucket...
>  * df663b2cd simplex-chat: Update to version 3.1.0                       5 minutes ago
> Updating 'zzz_anderlli0053' bucket...
> Updating files: 100% (3021/3021), done.
>  * 0f391276 Update cleanup-manifests.py                                  3 minutes ago
>  * c8b30a69 Various fixes                                                26 minutes ago
> Scoop was updated successfully!
> PS C:\Windows\System32\WindowsPowerShell\v1.0> scoop search obs-studio
> WARN  Error parsing JSON at C:\Users\Pulaski\.scoop\buckets\zzz_anderlli0053\bucket\processing.json.
> Results from local buckets...
> 
> Name             Version Source           Binaries
> ----             ------- ------           --------
> obs-studio-small 21.1.2  zzz_anderlli0053
> obs-studio       27.2.4  zzz_anderlli0053
> ```
> 
> the thing with processing.json is to be expected, but I'm curious why your Python installation freaked out.
> 
> Thank you for your efforts!


I will look at the processing.json to see what the problem is and no,
Thank you for writing the Python script and even opening the issue about multiple erroneus manifests at once, and not one-by-one.
