### ISSUE TITLE
[Bug]: Minibin changed url

### ISSUE THREAD

**Issue by tordenflesk** [anderlli0053/DEV-tools#116]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

minibin

### Expected/Current Behaviour

New url is https://e-sushi.net/minibin.zip

### Steps to Reproduce

```console
Scoop install Minibin
```

### Possible Solution

Update URL

### Scoop and Buckets Version

```console
Not relevant
```

### Scoop Config

```console
Not relevant
```

### PowerShell Version

```console
Not relevant
```

**Comment by anderlli0053** [comment]
Fixed in latest update https://github.com/anderlli0053/DEV-tools/commit/9147f24bc3fe0b4229cc48fa4827a94da798b749

Run `scoop update` and then try to install again via `scoop install minibin` or just use one command via joining: 

`scoop update && scoop install minibin`
