### ISSUE TITLE
xmcl@0.32.8: Can't shim 'xmcl.exe': File doesn't exist

### ISSUE THREAD

**Issue by SettingDust** [anderlli0053/DEV-tools#119]
The file name is `X Minecraft Launcher.exe` now

Reference: https://github.com/The-Simples/scoop-minecraft/blob/main/bucket/xmcl.json

**Comment by anderlli0053** [comment]
Fixed, run `scoop update` first and then reinstall it again

**Comment by anderlli0053** [comment]
Fixed in https://github.com/anderlli0053/DEV-tools/commit/924f19327f9fef74304205f53b8f759360a988d9
