### ISSUE TITLE
feishu wind rongdazhihuiyun  Choice 飞书 万得金融终端 荣大智慧云 Choice

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#12]
feishu & Wind financial &  rongdazhihuiyun  & Choice finanial 飞书&万得金融终端&荣大智慧云&Choice金融终端

## Package Request
 
 
 

~~1~~
~~feishu~~

~~**Name:** [feishu]~~

~~**Description:** [feishu]~~

~~**Homepage:** [https://www.feishu.cn/]~~

~~**Download link(s):** [https://sf3-cn.feishucdn.com/obj/ee-appcenter/b78084/Feishu-win32_ia32-5.18.5-signed.exe]~~
 
 
 
2    
wind  ( a financial data tool)

**Name:** [wind]

**Description:** [wind]

**Homepage:** [https://www.wind.com.cn]

**Download link(s):** [https://d-cdn.wind.com.cn/windnet/WFT_Setup_CHS.zip]
 
 
 
3   
 rongda zhihuiyun  (an online collaborative documents tool)

**Name:** [rongdazhihuiyun]

**Description:** [rongdazhihuiyun]

**Homepage:** [[http://www.rongdakeji.com/extend]

**Download link(s):** [https://download.rongdasoft.com/update/prod/250/Rd_IBSaas_V2.5.0.exe]
 
 
 
4 
Choice ( a financial data tool)

**Name:** [Choice]

**Description:** [Choice]

**Homepage:** [https://choice.eastmoney.com/]

**Download link(s):** [https://choiceupdates.eastmoney.com/Choice/OfflinePackage/6.2.0.0/ChoiceSetupLocal.exe]

Many thank!

**Comment by anderlli0053** [comment]
Run `scoop update && scoop install feishu`

**Comment by NoPKU** [comment]
> Run `scoop update && scoop install feishu`

Many thanks,  would you please add the other three frequently used tools to the bucket?

**Comment by anderlli0053** [comment]
> > Run `scoop update && scoop install feishu`
> 
> Many thanks, would you please add the other three frequently used tools to the bucket?

Will try to add them in.

**Comment by NoPKU** [comment]
> > > Run `scoop update && scoop install feishu`
> > 
> > 
> > Many thanks, would you please add the other three frequently used tools to the bucket?
> 
> Will try to add them in.

Thank you very much for adding them in.
Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address.
("C:\Program Files (x86)\Wind\bin\windnet.exe")
so now it can not be launched in the right way.
if installed right, it will be launched like in this picture and show the logging interface.
![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)

**Comment by anderlli0053** [comment]
@NoPKU  I've added those 3 programs, please update the scoop buckets and try to install each one and report back if everything works because i am pretty sure something won't work as expected :) .

**For updating Scoop buckets before installing any of the apps run:**

`scoop update`

then for installing each separate app:

**WIND FINANCIAL:**

`scoop install wind-financial`


**CHOICE:**

`scoop install choice`


**RONGDA ZHIHUIYUN:**

`scoop install rongda-zhihuiyun`


For testing purposes i did `scoop update && scoop install rongda-zhihuiyun choice wind-financial` and it somewhat worked.

**Comment by anderlli0053** [comment]
> > > > Run `scoop update && scoop install feishu`
> > > 
> > > 
> > > Many thanks, would you please add the other three frequently used tools to the bucket?
> > 
> > 
> > Will try to add them in.
> 
> Thank you very much for adding them in. Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address. ("C:\Program Files (x86)\Wind\bin\windnet.exe") so now it can not be launched in the right way. if installed right, it will be launched like in this picture and show the logging interface. ![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)


Thank you for reporting back, 

I am trying to guess at which executable is the right one to start and to create shortcut for.. Also i have a little problem because of the language barrier .

I thought that the right binary to launch is `bin\\WindNavigator.exe`, so the `WindNavigator.exe` , located in the `bin` folder

**Comment by NoPKU** [comment]
> > > > > Run `scoop update && scoop install feishu`
> > > > 
> > > > 
> > > > Many thanks, would you please add the other three frequently used tools to the bucket?
> > > 
> > > 
> > > Will try to add them in.
> > 
> > 
> > Thank you very much for adding them in. Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address. ("C:\Program Files (x86)\Wind\bin\windnet.exe") so now it can not be launched in the right way. if installed right, it will be launched like in this picture and show the logging interface. ![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)
> 
> Thank you for reporting back,
> 
> I am trying to guess at which executable is the right one to start and to create shortcut for.. Also i have a little problem because of the language barrier .
> 
> I've changed the launching binary to the one below:
> 
> I thought that the right binary to launch is `bin\\WindNavigator.exe`, so the `WindNavigator.exe` , located in the `bin` folder

Now it works, thank you very much, you are awesome!

**Comment by anderlli0053** [comment]
> > > > > > Run `scoop update && scoop install feishu`
> > > > > 
> > > > > 
> > > > > Many thanks, would you please add the other three frequently used tools to the bucket?
> > > > 
> > > > 
> > > > Will try to add them in.
> > > 
> > > 
> > > Thank you very much for adding them in. Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address. ("C:\Program Files (x86)\Wind\bin\windnet.exe") so now it can not be launched in the right way. if installed right, it will be launched like in this picture and show the logging interface. ![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)
> > 
> > 
> > Thank you for reporting back,
> > I am trying to guess at which executable is the right one to start and to create shortcut for.. Also i have a little problem because of the language barrier .
> > I've changed the launching binary to the one below:
> > I thought that the right binary to launch is `bin\\WindNavigator.exe`, so the `WindNavigator.exe` , located in the `bin` folder
> 
> Now it works, thank you very much, you are awesome!

Glad to hear that, thank you for reporting the issues

**Comment by NoPKU** [comment]
> > > > > > > Run `scoop update && scoop install feishu`
> > > > > > 
> > > > > > 
> > > > > > Many thanks, would you please add the other three frequently used tools to the bucket?
> > > > > 
> > > > > 
> > > > > Will try to add them in.
> > > > 
> > > > 
> > > > Thank you very much for adding them in. Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address. ("C:\Program Files (x86)\Wind\bin\windnet.exe") so now it can not be launched in the right way. if installed right, it will be launched like in this picture and show the logging interface. ![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)
> > > 
> > > 
> > > Thank you for reporting back,
> > > I am trying to guess at which executable is the right one to start and to create shortcut for.. Also i have a little problem because of the language barrier .
> > > I've changed the launching binary to the one below:
> > > I thought that the right binary to launch is `bin\\WindNavigator.exe`, so the `WindNavigator.exe` , located in the `bin` folder
> > 
> > 
> > Now it works, thank you very much, you are awesome!
> 
> Glad to hear that, thank you for reporting the issues

Now it works, thank you very much, you are awesome!

**Comment by anderlli0053** [comment]
> > > > > > > > Run `scoop update && scoop install feishu`
> > > > > > > 
> > > > > > > 
> > > > > > > Many thanks, would you please add the other three frequently used tools to the bucket?
> > > > > > 
> > > > > > 
> > > > > > Will try to add them in.
> > > > > 
> > > > > 
> > > > > Thank you very much for adding them in. Here I find a problem that the main program of Wind-Financial is Windnet.exe as you can see in the below address. ("C:\Program Files (x86)\Wind\bin\windnet.exe") so now it can not be launched in the right way. if installed right, it will be launched like in this picture and show the logging interface. ![WeChat Screenshot_20220813181545](https://user-images.githubusercontent.com/12542250/184479377-88f3791f-4de6-4580-8f14-0be985c664cb.png)
> > > > 
> > > > 
> > > > Thank you for reporting back,
> > > > I am trying to guess at which executable is the right one to start and to create shortcut for.. Also i have a little problem because of the language barrier .
> > > > I've changed the launching binary to the one below:
> > > > I thought that the right binary to launch is `bin\\WindNavigator.exe`, so the `WindNavigator.exe` , located in the `bin` folder
> > > 
> > > 
> > > Now it works, thank you very much, you are awesome!
> > 
> > 
> > Glad to hear that, thank you for reporting the issues
> 
> sorry to bother you, the problem still exists, the executable should be changed to _windnet.exe_



No problem really..  Will solve that in a few minutes

**Comment by NoPKU** [comment]
thank you very much

**Comment by anderlli0053** [comment]
@NoPKU  Seems like the `windnet.exe` doesn't launch, even though i changed the pointers from `WindNavigator.exe` to this one.. hmm 

You sure that the right one is `windnet.exe` ?

**Comment by NoPKU** [comment]
> @NoPKU Seems like the `windnet.exe` doesn't launch, even though i changed the pointers from `WindNavigator.exe` to this one.. hmm
> 
> You sure that the right one is `windnet.exe` ?

Yep, i installed it directly and checked the shortcut, it goes to ![WeChat Screenshot_20220813230021](https://user-images.githubusercontent.com/12542250/184499664-c72ff5d7-ac74-4a39-9b2e-fc9c2e2b1d46.png)

**Comment by anderlli0053** [comment]
> > @NoPKU Seems like the `windnet.exe` doesn't launch, even though i changed the pointers from `WindNavigator.exe` to this one.. hmm
> > You sure that the right one is `windnet.exe` ?
> 
> Yep, i installed it directly and checked the shortcut, it goes to ![WeChat Screenshot_20220813230021](https://user-images.githubusercontent.com/12542250/184499664-c72ff5d7-ac74-4a39-9b2e-fc9c2e2b1d46.png)


I see, i also see that the software is originally called with no flags / arguments, i've checked the original MSI file and the Scoop extracts it correctly 1:1, so i do not really know where the problem resides and why the binary won't start.. hmm.. 

Checking now with WinDBG.. maybe it will yield some results

**Comment by anderlli0053** [comment]
@NoPKU  also do other programs work?

**Comment by NoPKU** [comment]
> @NoPKU also do other programs work?

others are all fine

**Comment by anderlli0053** [comment]
@NoPKU  

As i have just found out that even though the startup program is windnet.exe, that program is not the one which runs as a main one; it only calls 3 others to run..

![3sa](https://user-images.githubusercontent.com/22171451/184501903-09785e3a-414b-4953-971d-ca22d924b515.PNG)

**Comment by anderlli0053** [comment]
@NoPKU  I think the error resides in the `LessMSI` tool, which Scoop uses to extract MSI installers... as i have said that the files do come out byte-to-byte the same, but the content is supposedly mangled...

Will try to rewrite the manifest for Wind, hope that will help!

**Comment by anderlli0053** [comment]
@NoPKU  I think i solved it, please run `scoop update && scoop install wind-financial-tool`

**Comment by NoPKU** [comment]
> @NoPKU I think i solved it, please run `scoop update && scoop install wind-financial-tool`
Yeah, now it is perfect, thank you very much!
