### ISSUE TITLE
Remove some manifests from this bucket!!!

### ISSUE THREAD

**Issue by Ryanjiena** [anderlli0053/DEV-tools#140]
Remove some manifests from this bucket!!!

https://github.com/anderlli0053/DEV-tools/commit/ed248a71a71ff5f6cd1890f70ba60c451294f8fc

#44 why???

**Comment by anderlli0053** [comment]
@Ryanjiena 

https://github.com/anderlli0053/DEV-tools/issues/44#issuecomment-1592661747

**Comment by anderlli0053** [comment]
@Ryanjiena 

All good now? I think i have cleared all of them
