### ISSUE TITLE
minibin@6.6.0.0: Hash check failed

### ISSUE THREAD

**Issue by tordenflesk** [anderlli0053/DEV-tools#147]
Hash check failed!
App:         XXX_anderlli0053/minibin
URL:         https://e-sushi.net/projects/minibin.zip
First bytes: 10 60 33 100 111 99 116 121
Expected:    cc597f8eaae568dabc274a1f250eb3d8396b99b4d9856674d493ffe2f693b110
Actual:      66bd0a5871af195c9f6cbfb4be4a7de696ec2760ec1b9cc2709263924b90751b

**Comment by tordenflesk** [comment]
Looks like the hash changes every time I try to install. Any way of bypassing the hash-check?

**Comment by anderlli0053** [comment]
> Looks like the hash changes every time I try to install. Any way of bypassing the hash-check? @anderlli0053

Hmm... Manifest can be edited and hash property removed.

**Comment by anderlli0053** [comment]
@tordenflesk  It works now

**Comment by anderlli0053** [comment]
Run `scoop update` and then install again
