### ISSUE TITLE
Streamlink Twitch GUI has the wrong package name

### ISSUE THREAD

**Issue by bastimeyer** [anderlli0053/DEV-tools#16]
Hi, I'm the author of [Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) and just found this via a Google search result on https://rasa.github.io/scoop-directory/search.

My application is packaged in your scoop bucket as `StreamlabsTwitchGUI-Portable`, which is wrong:
https://github.com/anderlli0053/DEV-tools/blob/f5d21ef722ff3b1c2057719a401642e3ae6231a8/bucket/StreamlabsTwitchGUI-Portable.json

It is however also packaged correctly as `streamlink-twitch-gui`:
https://github.com/anderlli0053/DEV-tools/blob/f5d21ef722ff3b1c2057719a401642e3ae6231a8/bucket/streamlink-twitch-gui.json

Since I am not a user of scoop or even Windows, I don't want to submit a PR with a removal of the incorrect/duplicate file, so I'm opening this issue instead and would like to kindly ask you to remove it yourself.

Thanks.

**Comment by anderlli0053** [comment]
Resolved in latest update,

Thank you for reporting the issue,

Regards,

Andrew
