### ISSUE TITLE
Delete bucket 

### ISSUE THREAD

**Issue by arch3rPro** [anderlli0053/DEV-tools#176]
please remove bucket https://github.com/arch3rPro/scoop-bucket

**Comment by arch3rPro** [comment]
please remove bucket https://github.com/arch3rPro/scoop-bucket

**Comment by anderlli0053** [comment]
I will try to list all the apps from your bucket and delete them as soon as I'll have some time.

**Comment by anderlli0053** [comment]
@arch3rPro also if you have some time you can create the list of all the apps that you wish to remove from your bucket and I'll create Python or Powershell script to do so, so it's faster done that way.

**Comment by arch3rPro** [comment]
https://github.com/search?q=repo%3Aanderlli0053%2FDEV-tools+path%3Aarch3rpro&type=code&p=1            for this

**Comment by anderlli0053** [comment]
So basically everything that has prefix or postfix of "arch3rpro"

**Comment by anderlli0053** [comment]
Done, 45 manifests removed

**Comment by arch3rPro** [comment]
thanks for removed，but there are  118 files  included by search code with 
https://github.com/search?q=repo%3Aanderlli0053%2FDEV-tools%20arch3rpro&type=code
please remove them，thanks a lot !!

**Comment by anderlli0053** [comment]
Will try to do when I get home; in about few hours!
19 Nov 2024, 05:04 by ***@***.***:
