### ISSUE TITLE
Duplicated manifests containing _(1) and _(1)_(1) #24

### ISSUE THREAD

**Issue by r15ch13** [anderlli0053/DEV-tools#178]
These last commits duplicated every manifest (ending in `_(1)` and `_(1)_(1)`) and may add more on the next run.
They also clutter the search on scoop.sh.

https://github.com/anderlli0053/DEV-tools/commit/947ee2daf6cf0a77750fd8d3a54a55545f5b64dc
https://github.com/okibcn/ScoopMaster/commit/b6263c42d1cf497fc34dab9d58d7b3a928842fc9

**Comment by anderlli0053** [comment]
Fixed by https://github.com/anderlli0053/DEV-tools/commit/94f5e6c7c459d6af1b1c245961b492bcaaa7e77e
