### ISSUE TITLE
[Request] please add PDFgear  🫡

### ISSUE THREAD

**Issue by aka-phrankie** [anderlli0053/DEV-tools#188]
**Name:** [pdfgear]

**Description:** [Read, edit, convert, merge, and sign PDF files across devices, for completely free and without signing up.]

**Homepage:** [https://www.pdfgear.com/]

**Download link(s):** [https://www.pdfgear.com/download/pdfgear_setup_v2.1.0.exe]

**Some indication of popularity/repute:**  [Get more practical video tutorials on the [PDFgear YouTube Channel](https://www.youtube.com/channel/UCbagL-6l9QZPfGE7_9WVfBw)]
5 BEST PDF Editors in 2023 (One is REALLY FREE!)
Vision ：
Revolutionizing the way people interact with PDFs.

We believe everyone has access to the tools they need, which is why we're currently offering PDFgear for free. We take privacy seriously and ensure all data is secure.

**Comment by anderlli0053** [comment]
Why close the issue? As I see that nobody added the requested manifest, including me as I don't have much time.

**Comment by aka-phrankie** [comment]
Thank you for your reply. I'm sure you are a busy developer and i do not want to add any unnecessary burden for you.

Therefore, I think requesting some other buckets to try might be better for now. Closing the request temporarily would not be a bad option.

Exploring alternative solutions could help determine if there are any good fit options without extra workload. And closing it for now allows you to come back to it later should your needs or timelines change.

Please don't feel obligated to continue assisting if it starts to take up too much of your time. I appreciate you considering my initial question,If you have time and bandwidth available in the future, please feel free to reopen this issue so we can continue exploring options.

**Comment by anderlli0053** [comment]
@aka-phrankie 

I added the manifest for this app -  in case you dont already have this bucket amongst your scoop buckets run `scoop update && scoop bucket add anderlli0053_DEV-tools https://github.com/anderlli0053/DEV-tools && scoop install anderlli0053_DEV-tools/upnqr` .
