### ISSUE TITLE
git-filter-repo@2.34.0: decompress error

### ISSUE THREAD

**Issue by zero617** [anderlli0053/DEV-tools#20]
Extracting v2.34.0.zip ... ERROR Exit code was 2!
Failed to extract files from D:\Software\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip.
Log file:
  D:\Software\scoop\apps\git-filter-repo\2.34.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/anderlli0053/DEV-tools/issues/new?title=git-filter-repo%402.34.0%3a+decompress+error

**Comment by anderlli0053** [comment]
@zero617  This app requires admin / elevated privileges to install and uninstall.

It works fine when you run the console as admin.
