### ISSUE TITLE
The software version has not been updated for a long time!

### ISSUE THREAD

**Issue by tianlongJ** [anderlli0053/DEV-tools#206]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by anderlli0053** [comment]
@tianlongJ  What software exactly?

**Comment by tianlongJ** [comment]
> @tianlongJ What software exactly?

For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems

**Comment by anderlli0053** [comment]
> > @tianlongJ What software exactly?
> 
> For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems

BOT usually updates the manifests, but sometimes it stalles for unknown reasons and updates it after some time or even none at all. I don't know what is going on; and this is happening in other buckets too, even official ones

**Comment by tianlongJ** [comment]
> > > @tianlongJ What software exactly?
> > 
> > 
> > For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems
> 
> BOT usually updates the manifests, but sometimes it stalles for unknown reasons and updates it after some time or even none at all. I don't know what is going on; and this is happening in other buckets too, even official ones

Is it possible that it is caused by the file hardware-bios.json? I see stackoverflow when reading this file in actions.

**Comment by anderlli0053** [comment]
> > > > @tianlongJ What software exactly?
> > > 
> > > 
> > > For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems
> > 
> > 
> > BOT usually updates the manifests, but sometimes it stalles for unknown reasons and updates it after some time or even none at all. I don't know what is going on; and this is happening in other buckets too, even official ones
> 
> Is it possible that it is caused by the file hardware-bios.json? I see stackoverflow when reading this file in actions.

Maybe, i'll push a fix if that is even it, but thank you anyways 😄

**Comment by tianlongJ** [comment]
> > > > > @tianlongJ What software exactly?
> > > > 
> > > > 
> > > > For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems
> > > 
> > > 
> > > BOT usually updates the manifests, but sometimes it stalles for unknown reasons and updates it after some time or even none at all. I don't know what is going on; and this is happening in other buckets too, even official ones
> > 
> > 
> > Is it possible that it is caused by the file hardware-bios.json? I see stackoverflow when reading this file in actions.
> 
> Maybe, i'll push a fix if that is even it, but thank you anyways 😄



> > > > > @tianlongJ What software exactly?
> > > > 
> > > > 
> > > > For example, Oraclejdk, Nodejs, other software may also have this problem. The recent bucket synchronization seems to have problems
> > > 
> > > 
> > > BOT usually updates the manifests, but sometimes it stalles for unknown reasons and updates it after some time or even none at all. I don't know what is going on; and this is happening in other buckets too, even official ones
> > 
> > 
> > Is it possible that it is caused by the file hardware-bios.json? I see stackoverflow when reading this file in actions.
> 
> Maybe, i'll push a fix if that is even it, but thank you anyways 😄

I should first thank you for maintaining this bucket and saving us time looking for other buckets and programs, thanks for the effort
