### ISSUE TITLE
bandizip@7.32: hash check failed

### ISSUE THREAD

**Issue by theSprog** [anderlli0053/DEV-tools#229]
Installing 'bandizip' (7.32) [64bit] from anderlli0053_DEV-tools bucket
Loading BANDIZIP-PORTABLE.ZIP from cache
Checking hash of BANDIZIP-PORTABLE.ZIP ... ERROR Hash check failed!
App:         anderlli0053_DEV-tools/bandizip
URL:         https://dl.bandisoft.com/bandizip.std/BANDIZIP-PORTABLE.ZIP
First bytes: 50 4B 03 04 14 00 02 00
Expected:    2a5da2d012781d22833c6397c3eb89d3242c609e8453f144f623608b757135ee
Actual:      d0e3659f5f63c9f377d3e6b438fc65d10b15179fac5e88032f96fd35b0d940c4

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/anderlli0053/DEV-tools/issues/new?title=bandizip%407.32%3a+hash+check+failed

**Comment by theSprog** [comment]
What? 
The bot closed this as completed?

**Comment by anderlli0053** [comment]
> What? The bot closed this as completed?

The bot automatically updated the invalid hash from which you had the error from. ( https://github.com/anderlli0053/DEV-tools/commit/ebb5d4c7bc2374bf3a0da5786eebdef6e9b5b069 ) 

Now before anything you just run `scoop update` and then try to install it again, so the Scoop manifest repositories on your PC/Laptop refresh.

If you use Powershell 7 or newer you can use `&&` to do multiple things via one "command".

`scoop update && scoop install bandizip`

**Comment by theSprog** [comment]
Ok, I see it now.
I am a new hand for scoop, and thank you for your explain.

**Comment by anderlli0053** [comment]
> Ok, I see it now. I am a new hand for scoop, and thank you for your explain.

No problem
