### ISSUE TITLE
[Request]  Add QuArK tool

### ISSUE THREAD

**Issue by anderlli0053-storage** [anderlli0053/DEV-tools#24]
### Information

**Name:** [name of new package]

**Description:** [clear and concise details of what it is]

**Homepage:** [a URL/link]

**Download link(s):** [URL(s)/link(s)]

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by anderlli0053** [comment]
Added in latest update... Run `scoop update && scoop install quark`
