### ISSUE TITLE
update shoko-desktop

### ISSUE THREAD

**Issue by aicynide** [anderlli0053/DEV-tools#250]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by anderlli0053** [comment]
@aicynide 

Fixed by https://github.com/anderlli0053/DEV-tools/commit/0f42a916f2459d6f5614f2a0d4e9211dcdd95b8a and https://github.com/anderlli0053/DEV-tools/commit/4a81b488d41a4bb9874eccaef45a758d9abed62c


Run `scoop update` and then try to install it again
