### ISSUE TITLE
connection attempt failed installing 'veracrypt-Portable' (1.25.9) [64bit]

### ISSUE THREAD

**Issue by kiksilog** [anderlli0053/DEV-tools#26]
Installing 'veracrypt-Portable' (1.25.9) [64bit] from DEV-Tools bucket
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:162.243.236.235]:443 (download3.portableapps.com:443)
URL https://download3.portableapps.com/portableapps/VeraCryptPortable/VeraCryptPortable_1.25.9.paf.exe?20190321#/dl.7z is not valid

**Comment by anderlli0053** [comment]
> Installing 'veracrypt-Portable' (1.25.9) [64bit] from DEV-Tools bucket A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:162.243.236.235]:443 (download3.portableapps.com:443) URL https://download3.portableapps.com/portableapps/VeraCryptPortable/VeraCryptPortable_1.25.9.paf.exe?20190321#/dl.7z is not valid

Thanks for the report 👍🏻 

Resolved in the latest update..

Run `scoop update && scoop install DEV-Tools/veracrypt-portable`
