### ISSUE TITLE
[Bug]: SordumWindowsUpdateBlocker-Portable installation failed

### ISSUE THREAD

**Issue by nukhes** [anderlli0053/DEV-tools#267]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

SordumWindowsUpdateBlocker-Portable

### Expected/Current Behaviour

Sordum changed the download link for their Windows Update Blocker software, which caused the previously configured download URL and hash in the Scoop manifest to break. As a result, the software could no longer be downloaded, and the hash validation failed during installation, leading to errors when attempting to install or update the software through Scoop.

### Steps to Reproduce

```console
scoop install SordumWindowsUpdateBlocker-Portable
```

### Possible Solution

The solution is to modify the current link to the new download link, extract the file correctly and modify the hash

### Scoop and Buckets Version

```console
'anderlli0053_DEV-tools' bucket:
a1e47b865e (HEAD -> master, origin/master, origin/HEAD) SordumWindowsUpdateBlocker-Portable@1.8: Fix hash (Closes #266)
```

### Scoop Config

```console
last_update           scoop_repo                              scoop_branch aria2-warning-enabled
-----------           ----------                              ------------ ---------------------
11/16/2024 9:16:49 AM https://github.com/ScoopInstaller/Scoop master                       False
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anderlli0053** [comment]
Did you try to refresh Scoop repos with `scoop update` and then try to install again? Cause it should work now since i've fixed this 30-something minutes ago
