### ISSUE TITLE
[Request] add flicker list

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#27]
### Information

**Name:** flicker list

**Description:** A different kind of hover list software

**Homepage:**https://flicker.cool/

**Download link(s):** https://static.vifird.com/flicker/download/stable/3.6.0/win32_x32/Flicker%20List_Setup_3.6.0.exe

**Some indication of popularity/repute:**Simple design, powerful

**Comment by anderlli0053** [comment]
Done, run `scoop update && scoop install flickerlist`
