### ISSUE TITLE
[Request] add AliWorkbench

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#28]
### Information

**Name:** [name of new package] AliWorkbench

**Description:** [clear and concise details of what it is] One-stop merchant workbench to meet merchants' full-scene business requirements

**Homepage:** [a URL/link] https://work.taobao.com/

**Download link(s):** [URL(s)/link(s)]  https://work.taobao.com/download.html

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by anderlli0053** [comment]
Done, run `scoop update && scoop install ali-workbench`
