### ISSUE TITLE
[Request] add Excel Regular Tool

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#29]
### Information

**Name:** Excel Regular Tool

**Description:** Regular extract, replace, locate, filter

**Homepage:** https://github.com/liuyi91/Excel

**Download link(s):** https://sixtyone.lanzoux.com/b015cpfji

**Some indication of popularity/repute:** https://github.com/liuyi91/Excel

**Comment by anderlli0053** [comment]
Hello @usnake , the Excel Regular Tool archives are password protected, do you have the password to these archives? Without the password they cannot be extracted, bruteforce attack from me is / can be a violation of their EULA

**Comment by anderlli0053** [comment]
@usnake  The last version that can be normally extracted without the password is 1.5.0

**Comment by anderlli0053** [comment]
Done, I've added the latest unprotected version - 1.5.0,

Run `scoop update && scoop install excel-regular-tool`

**Comment by usnake** [comment]
@anderlli0053 password:   3300372390

**Comment by anderlli0053** [comment]
Updated the manifest, run `scoop update && scoop install excel-regular-tool`
