### ISSUE TITLE
[Request] add sunlogin full

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#30]
### Information

**Name:** sunlogin full

**Description:** Remote Office - Remote Operations and Maintenance - Technical Support - Remote Gaming - Remote Design

**Homepage:** https://sunlogin.oray.com/

**Download link(s):** https://sunlogin.oray.com/download?categ=personal

**Some indication of popularity/repute:** 

I see that this bucket already has sunlogin, but it is not the full version, please add the full version of the software, the version number is V 12.6.0.49095（2022.08）

**Comment by anderlli0053** [comment]
@usnake  I have added the manifests for the said version (_12.6.0.49095_) , you can use `scoop update && scoop install SunLogin`

**Comment by anderlli0053** [comment]
Thanks for the suggestions!
