### ISSUE TITLE
[Request] add clipboard-online

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#31]
### Information

**Name:** clipboard-online

**Description:** clipboard-online is an application to share cilpboard text between Windows and iOS

**Homepage:** https://github.com/YanxinTang/clipboard-online

**Download link(s):** https://github.com/YanxinTang/clipboard-online

**Some indication of popularity/repute:** none

**Comment by anderlli0053** [comment]
@usnake  This already exists in this bucket, maybe you have the old version, run `scoop update` and then `scoop install anderlli0053_DEV-tools/clipboard-online` or you can do it within one line like `scoop update && scoop install anderlli0053_DEV-tools/clipboard-online`
