### ISSUE TITLE
[Request] add CLaunch

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#32]
### Information

**Name:** CLaunch

**Description:** CLaunch is a quick launch management tool that is lightweight, compact, fast, convenient and feature-rich

**Homepage:** https://hp.vector.co.jp/authors/VA018351/en/claunch.html

**Download link(s):** https://hp.vector.co.jp/authors/VA018351/en/claunch.html

**Some indication of popularity/repute:** none

**Comment by anderlli0053** [comment]
Done, you can test 2 manifests for the same **CLAUNCH**

One is named _**claunch**_ and another is named **_claunch2_**

So the main one is _**claunch**_, you should go with that. The other one is just for testing purposes, but it should work too, although the latter (claunch2) doesn't have the autoupdate function.

**Comment by usnake** [comment]
> Done, you can test 2 manifests for the same **CLAUNCH**
> 
> One is named _**claunch**_ and another is named **_claunch2_**
> 
> So the main one is _**claunch**_, you should go with that. The other one is just for testing purposes, but it should work too, although the latter (claunch2) doesn't have the autoupdate function.

thanks a lot

**Comment by anderlli0053** [comment]
You're welcome :)
