### ISSUE TITLE
[Request] add AHK Studio

### ISSUE THREAD

**Issue by usnake** [anderlli0053/DEV-tools#34]
### Information

**Name:** AHK Studio

**Description:** AHK Studio is an IDE (Integrated development environment) for AutoHotkey

**Homepage:** https://www.maestrith.com/ahk-studio/

**Download link(s):** https://www.maestrith.com/ahk-studio/

**Some indication of popularity/repute:** none

**Comment by anderlli0053** [comment]
@usnake I just want to remind that there is no executable file to link to in the ZIP download link, except for the DLL, that is useless by itself. I am using the official download link -> [Github ZIP](https://github.com/maestrith/AHK-Studio/archive/master.zip)

**_For now i will add this, but cannot shim it or create the shortcut, because there are no known executables `.exe`, `.com`, `.msi`... not even scripts like `.sh`, `.bat` and `.cmd`, ..._**

**Comment by usnake** [comment]
> @usnake I just want to remind that there is no executable file to link to in the ZIP download link, except for the DLL, that is useless by itself. I am using the official download link -> [Github ZIP](https://github.com/maestrith/AHK-Studio/archive/master.zip)
> 
> **_For now i will add this, but cannot shim it or create the shortcut, because there are no known executables `.exe`, `.com`, `.msi`... not even scripts like `.sh`, `.bat` and `.cmd`, ..._**

AHK-Studio.ahk is an executable file after the installation of autohotkey

**Comment by anderlli0053** [comment]
> > @usnake I just want to remind that there is no executable file to link to in the ZIP download link, except for the DLL, that is useless by itself. I am using the official download link -> [Github ZIP](https://github.com/maestrith/AHK-Studio/archive/master.zip)
> > **_For now i will add this, but cannot shim it or create the shortcut, because there are no known executables `.exe`, `.com`, `.msi`... not even scripts like `.sh`, `.bat` and `.cmd`, ..._**
> 
> AHK-Studio.ahk is an executable file after the installation of autohotkey


Oh.. i will try to shim and shortcut it

**Comment by anderlli0053** [comment]
I'll also add suggestion for installing autohotkey beforehand, so it should print out via `scoop info ahk-studio`

**Comment by usnake** [comment]
> I'll also add suggestion for installing autohotkey beforehand, so it should print out via `scoop info ahk-studio`

Very good, thank you for your contribution

**Comment by anderlli0053** [comment]
> > I'll also add suggestion for installing autohotkey beforehand, so it should print out via `scoop info ahk-studio`
> 
> Very good, thank you for your contribution

Done, try it now, also delete previous versions of this same app if you installed it when i was half-ready with it :) 

To uninstall use `scoop uninstall ahk-studio` you can also clean up your apps with `scoop cleanup * && scoop cache rm *`

Run `scoop update && scoop install ahk-studio`

No problem :)
