### ISSUE TITLE
MameUI Download URL Broken

### ISSUE THREAD

**Issue by isavegas** [anderlli0053/DEV-tools#40]
## Bug Report

MameUI

### Current Behaviour

Unable to install due to 404 when attempting to fetch archive. Download URL has been changed.

### Expected Behaviour

Package should correctly download and install.

### Additional context/output

N/A

### Possible Solution

Change download URL in manifest. Fix has been tested on my machine, and hash still matches. File has simply been moved.

I can easily issue a PR to fix it, but the PR template specifies that a corresponding issue is required.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Additional software:** N/A

#### Scoop Configuration

```json
{
  "lastupdate": "2022-10-07T04:00:55.4267401-05:00",
  "aria2": "aria2-enabled",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": false,
  "MSIEXTRACT_USE_LESSMSI": true,
  "aria2-warning-enabled": false
}
```

**Comment by anderlli0053** [comment]
@isavegas  Thanks for reposting the issues.. Strange thing is that the bots that are responsible for these things (updating, formatting and maintaining specific manifests) do not do anything about that... Will try to look at that too in the future..


Is this the correct link? -> http://www.mameui.info/MAMEUI248.7z  ;

The one that states `MAMEUI .248 'Final' (2022.09.27)` ?

For now i'll add the mentioned link and file to the manifest

**Comment by isavegas** [comment]
Yes, they appear to have simply renamed the file. The hash still matches. That should correct the issue. 👍

**Comment by anderlli0053** [comment]
I think i've fixed it in the latest update.. Run `scoop update && scoop install mameui`  and see if it works for you. I'll close the issues for now, but can reopen it if something is not working properly and if it can be fixed from my end.
