### ISSUE TITLE
Thunder@11.1.12.1692: download via aria2 failed

### ISSUE THREAD

**Issue by tille1229** [anderlli0053/DEV-tools#41]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://scoop-zapps.ziiyc.com/d/Thunder/Thunder-11.1.12.1692.exe#/setup.exe
    referer=https://scoop-zapps.ziiyc.com/d/Thunder/Thunder-11.1.12.1692.exe#/
    dir=D:\Applications\Scoop\cache
    out=Thunder#11.1.12.1692#https_scoop-zapps.ziiyc.com_d_Thunder_Thunder-11.1.12.1692.exe_setup.exe

ERROR & 'D:\Applications\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Applications\Scoop\cache\Thunder.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=18920 --continue --summary-interval=0 --auto-save-interval=1

**Comment by anderlli0053** [comment]
This cannot be fixed, because i've received messages from the original authors, wanting me to remove their software from this bucket.
