### ISSUE TITLE
Apps request: gclone

### ISSUE THREAD

**Issue by areen-c** [anderlli0053/DEV-tools#43]
### Information

**Name:** gclone

**Description:** 
A modified version of the [rclone](https://github.com/rclone/rclone)
Implement [donwa/gclone](https://github.com/donwa/gclone) to sync with rclone version
Provide dynamic replacement sa file support for google drive operation

**Homepage:** https://github.com/dogbutcat/gclone

**Download link(s):** https://github.com/dogbutcat/gclone/releases

**Comment by anderlli0053** [comment]
Done, this should work (for now at least), but the manifest should be fixed in the future,

Run `scoop update && scoop install gclone`
