### ISSUE TITLE
tencent-meeting can not launch 

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#47]
## Bug Report

**Package Name:tencent-meeting

Rename-Item : Cannot process argument because the value of argument "path" is not valid. Change the value of the
"path" argument and run the operation again.
At line:1 char:1
+ Rename-Item -Path "$dir\`$_*" -NewName "$version" -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand

**Comment by anderlli0053** [comment]
Fixed, run `scoop uninstall tencent-meeting && scoop cleanup * && scoop update && scoop install tencent-meeting`
