### ISSUE TITLE
iFind creates too many shortcuts

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#48]
Thank you very muck for adding iFind to the bucket.
sorry to bother you but there is a very small problem, which is that it creates too many shortcuts to the start-list, one shortcut only for iFinD.exe will be OK

## Bug Report

**Package Name:iFind.exe

we need **Creating shortcut for iFinD (iFinD.exe)**

these are all unnecessary:
Creating shortcut for cefclient (cefclient.exe)
Creating shortcut for glt (glt.exe)
Creating shortcut for HXReporter (HXReporter.exe)
Creating shortcut for iFinDHelper (iFinDHelper.exe)
Creating shortcut for iFinDHQDataFeed (iFinDHQDataFeed.exe)
Creating shortcut for iFinDLP (iFinDLP.exe)
Creating shortcut for iFinDsj (iFinDsj.exe)
Creating shortcut for iFinDUP (iFinDUP.exe)
Creating shortcut for iFinDWeb (iFinDWeb.exe)
Creating shortcut for JiGouBan (JiGouBan.exe)
Creating shortcut for Screen Capture (ScreenCapture.exe)
Creating shortcut for Screen Recording (ScreenRecording.exe)
Creating shortcut for SpadeA (SpadeA.exe)
Creating shortcut for Ths Capture Tools (ThsCaptureTools.exe)
Creating shortcut for ThsSysDiagnoseTool (ThsSysDiagnoseTool.exe)

**Comment by anderlli0053** [comment]
Fixed, run this command to uninstall the Ifind, update the manifest cache and reinstall it:  `scoop uninstall ifind && scoop update && scoop install ifind`
