### ISSUE TITLE
tencent-meeting.exe, rongda-zhihuiyun.exe, wind-financial-tool.exe  need to be updates 

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#49]
## updates 

1**Package Name: tencent-meeting.exe   V3.11.6.402   [https://updatecdn.meeting.qq.com/cos/947a8fd1faf0d491148980605952049b/TencentMeeting_0300000000_3.11.6.402.publish.exe]

2**Package Name: rongda-zhihuiyun.exe   V2.8.6   [https://download.rongdasoft.com/update/prod/280/Rd_IBSaas_V2.8.6.exe]

3**Package Name: wind-financial-tool.exe   V22.8.0   [https://d-cdn.wind.com.cn/windnet/WFT_Setup_CHS.zip]

**Comment by NoPKU** [comment]
thank you very much

**Comment by anderlli0053** [comment]
@NoPKU  Thank you for reporting, will try to update them and try to write RegEx-es. Cannot see the manifests right now as I'm on the phone, but it is funny how the Python bots, who are supposed to update the packages automatically, don't update them at all. Right now I'm at work, will try to make sense about it in about 8-10 hours from now.

**Comment by anderlli0053** [comment]
- [x] Updated **rongda-zhihuiyun**
- [ ] Updated **wind-financial-tool**
- [ ] Updated **tencent-meeting**
