### ISSUE TITLE
paperwork@2.1.1: download via aria2 failed

### ISSUE THREAD

**Issue by Ama1999** [anderlli0053/DEV-tools#61]
#### Scoop Configuration

```json
{
  "last_update": "2022-12-05T11:06:58.6929843+01:00",
  "use_external_7zip": true,
  "use_lessmsi": true,
  "autostash_on_conflict": true,
  "root_path": "#VALIDPATH",
  "global_path": "#VALIDPATH",
  "cache_path": "#VALIDPATH",
  "aria2-enabled": true,
  "aria2-warning-enabled": false,
  "aria2-retry-wait": "5",
  "aria2-split": "12",
  "aria2-max-connection-per-server": "12",
  "aria2-min-split-size": "6M",
  "virustotal_api_key": "#SECRET",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "develop"
}
```
_Some fields were blanked out for privacy and/or security reasons, this should not affect the issue statement at all._

#### Relevant Console Output

<details>
<summary>Contents of console output when attempting install</summary>
ERROR Download failed! (Error 3) Resource was not found
ERROR https://download.openpaper.work/windows/x86/paperwork-master-ea1b8b01.zip
    referer=https://download.openpaper.work/windows/x86/
    dir=#VALIDPATH\scoop-cache
    out=paperwork#2.1.1#https_download.openpaper.work_windows_x86_paperwork-master-ea1b8b01.zip

ERROR & '#VALIDPATH\scoop\apps\aria2\current\aria2c.exe' --input-file='#VALIDPATH\scoop-cache\paperwork.txt' --user-agent=#VALIDUA --allow-overwrite=true --auto-file-renaming=false --retry-wait=5 --split=12 --max-connection-per-server=12 --min-split-size=6M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=2708 --continue --summary-interval=0 --auto-save-interval=1
</details>

#### Potential Mechanism

Developer of package seems to have changed the link pipeline to the resource. This may have been due to changes to versioning (following from below)

#### Potential Fix

Suggested change to the pipeline location to __https://download.openpaper.work/windows/installer/paperwork_stable_installer.exe__
This seems to be the (new) correct URL for the download of the _stable version_ of the package. Seeing as the previous version indicated 'master' version, it is unclear/unknown to me whether this would be the same versioning. If not, pulling from the resource GitLab may be a better idea, since it's more consistent and reliable.

**Comment by anderlli0053** [comment]
I assume that the correct AND USEFUL download location is this:  https://download.openpaper.work/windows/amd64/paperwork-master-latest.zip

since it is just ZIP, which just need to be extracted, more or less

**Comment by anderlli0053** [comment]
Updated the manifest
