### ISSUE TITLE
[Bug]: Upscayl new update to 2.0.0 doesn't install, error 404

### ISSUE THREAD

**Issue by okibcn** [anderlli0053/DEV-tools#69]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Upscayl

### Expected/Current Behaviour

Upscayl new update from v1.5.5 to v2.0.0 has changed the installer filename convention used so far. So the package is incorrectly trying to download the installer from:
`https://github.com/upscayl/upscayl/releases/download/v2.0.0/Upscayl-Setup-2.0.0.exe`

but the installed URL is actually:
`https://github.com/upscayl/upscayl/releases/download/v2.0.0/upscayl-2.0.0-win.exe`

### Steps to Reproduce

```console
PS> scoop update upscayl
upscayl: 1.5.5 -> 2.0.0
Updating one outdated app:
Updating 'upscayl' (1.5.5 -> 2.0.0)
Downloading new version
OperationStopped: C:\Users\Oki\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

### Possible Solution

Replace the download URL from:
`https://github.com/upscayl/upscayl/releases/download/v2.0.0/Upscayl-Setup-2.0.0.exe `
to:
`https://github.com/upscayl/upscayl/releases/download/v2.0.0/upscayl-2.0.0-win.exe`

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'dev' bucket:
e6686594f (HEAD -> master, origin/master, origin/HEAD) scoop-directory: Update to version 2022-12-26-00-47-44

'echo' bucket:
a597f8d (HEAD -> main, origin/main, origin/HEAD) iobituninstaller:12.2.0.7

'main' bucket:
c101499a7 (HEAD -> master, origin/master, origin/HEAD) pnpm: Update to version 7.20.0

'zapps' bucket:
844ead9 (HEAD -> master, origin/master, origin/HEAD) Auto Update
```

### Scoop Config

```console
last_update           : 2022-12-25 7:47:14 PM
aria2-warning-enabled : False
alias                 : @{allin=scoop-allin}
scoop_repo            : https://github.com/ScoopInstaller/Scoop
scoop_branch          : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.25267
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

N/A

**Comment by anderlli0053** [comment]
It is solved now, run `scoop update && scoop install upscayl` again or you can explicitly use the alias like `scoop update && scoop install DEV-Tools/upscayl`
