### ISSUE TITLE
[Question] How do you manage to maintain such a large Bucket?

### ISSUE THREAD

**Issue by cesaryuan** [anderlli0053/DEV-tools#74]
Sorry to bother you, but first of all, thank you very much for maintaining this Bucket with so many Apps!

I'm just curious, how do you manage to maintain such a huge Bucket? So far you have more than 10,000 manifest in your repository, did you add them one by one by yourself? If so, that's a huge amount of work.

Or does your repository have some automated measures to automatically grab manifest from other scoop buckets in Github?

Just a few questions, sorry if I'm bothering you. Thanks again!

**Comment by anderlli0053** [comment]
@cesaryuan  No problem at all.

First i started to adding them myself, when i created some manifests i added them in chunks of 5 or something like that. Then later when the bucket repo became big i wrote and co-wrote some Python, Powershell and Batch scripts and updated the CI actions system (YMLs) to update some of the manifests (which their own manifests do not), and fetch the changes from some other repos too. In general meaning that this is a very big collection of my own manifests and the manifests that the [BOT]s fetch from different repos, mostly official and some unofficial ones, then compare the changes with the existing manifests(if they exist), if they do not they just simply copy them and test them, if they do exist the version string is compared, if it is lower version than the ones already in the repository, it is ignored, if it is higher the pre-existing lower versioned manifest is overwritten by the one preceeding it by its version string.

**Comment by cesaryuan** [comment]
Thank you for your explanation!

**Comment by anderlli0053** [comment]
No problem, you're welcome!
