### ISSUE TITLE
MicrosoftVisualStudioCommunity2022 - Install this package has a problem

### ISSUE THREAD

**Issue by dong-lufei** [anderlli0053/DEV-tools#80]
scoop install MicrosoftVisualStudioCommunity2022-Install

```
Scoop was updated successfully!
Installing 'MicrosoftVisualStudioCommunity2022-Install' (17.4.4) [64bit] from dev-tools bucket
Loading vs_community.exe from cache.
Checking hash of vs_community.exe ... ok.
Running installer script...
ERROR Exit code was 87!
ERROR Exit code was 87!
Linking D:\scoop_user_apps\apps\MicrosoftVisualStudioCommunity2022-Install\current => D:\scoop_user_apps\apps\MicrosoftVisualStudioCommunity2022-Install\17.4.4
'MicrosoftVisualStudioCommunity2022-Install' (17.4.4) was installed successfully!
```
There were several errors during installation. Finally, when the installation was complete, it should be in the D disk path that I set up, but the main file was in the C disk

**Comment by anderlli0053** [comment]
@dong-lufei  Related to https://github.com/ACooper81/scoop-apps/issues/145

**Comment by anderlli0053** [comment]
Closing as per https://github.com/ACooper81/scoop-apps/issues/145#issuecomment-1407356710  (at least for the time being, if nothing changes in the meantime)
