### ISSUE TITLE
hashtab@6.0.0.34: hash check failed

### ISSUE THREAD

**Issue by Fumeze** [anderlli0053/DEV-tools#99]
Installing 'hashtab' (6.0.0.34) [64bit] from DEV-Tools bucket

Checking hash of HashTab_v6.0.0.34_Setup.exe ... ERROR Hash check failed!
App:         DEV-Tools/hashtab
URL:         http://implbits.com/products/hashtab/HashTab_v6.0.0.34_Setup.exe#/dl.7z
First bytes: 3C 21 64 6F 63 74 79 70
Expected:    85caa9ea0bb91da273e4d02b5f0a1c1736cc7314c4f2c839882339cc69ddaf10
Actual:      e4759a977d79acbf2b27a5509a0bbf92b16672bfc7d81c23800034c84bcd2e51

**Comment by anderlli0053** [comment]
@Fumeze  This program was deprecated from the official site, but there are alternatives, namely [OpenHashTab](https://github.com/namazso/OpenHashTab) is one of them, it is also available through Scoop buckets, via this bucket `scoop install anderlli0053_DEV-tools/openhashtab-np` or via "official" one as `scoop install nonportable/openhashtab-np`

**Comment by Fumeze** [comment]
I got it, thank you👌

**Comment by anderlli0053** [comment]
> I got it, thank you👌

You're welcome!
